name: Auto-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install
        run: make install
      - name: test
        run: make test
      - name: lint
        run: make lint